[package]
name = "kernel"
build = "build.rs"

[[bin]]
name = "onish-kernel"
path = "src/boot.rs"

[build-dependencies]
cc = "1.0"

[profile.release]
panic = "abort"
lto = true        # Link Time Optimization (makes the image smaller)